#!/bin/bash

# Define the file name
file_name="7-file"

# Define the content
content="Best School"

# Create the file with the specified content
echo -e "$content" > "$file_name"

# Add a newline to the end of the file
echo >> "$file_name"

# Print a message indicating the file has been created
echo "File '$file_name' created with content: '$content'"
